#spring:
#  datasource:
#    url: jdbc:h2:mem:library
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
#  sql:
#    init:
#      platform: dev
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: none
#    defer-datasource-initialization: true
#
#  h2:
#    console:
#      path: /h2-console
#      settings:
#        web-allow-others: true
#      enabled: true

spring:
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      database: library
      port: 27017
      host: localhost